### ISSUE TITLE
Linux build system not working atm

### ISSUE THREAD

**Issue by wiebow** [Swoffa/SublimeKickAssemblerC64#1]
Hi,

I have tried running the build system on Linux Mint (17.3) and I get the following error: **Error: Could not find or load main class cml.kickass.KickAssembler**
I know for sure that the CLASSPATH variable is set correctly to the folder containing the KickAss.jar file.

Using the command java -jar KickAss.jar runs the assembler correctly.

So my question is : can the build system be changed, or is there a way to make this work correctly on Linux.
FYI: I´ve used this installation info: https://packagecontrol.io/packages/Kick%20Assembler%20(C64)

**Comment by wiebow** [comment]
Turns out that "fullpath to the KickAss.jar file" also must include the file name. So not just the path. It's working here now, no worries.

**Comment by Swoffa** [comment]
Great to hear! Sorry for not replying earlier, but that was my guess too.

**Comment by bibbleBobble** [comment]
Dang, I'm getting this error now with CLASSPATH set to the full path of KickAss.jar. I've double checked the path is correct, but no luck. Sigh, will RTFM I guess.

**Comment by Swoffa** [comment]
@bibbleBobble 
Some comments here that might help you:
https://goatpower.org/projects-releases/sublime-package-kick-assembler-c64/
