### ISSUE TITLE
Extraneous ) at the end of the mon file name

### ISSUE THREAD

**Issue by daleicious** [Swoffa/SublimeKickAssemblerC64#14]
https://github.com/Swoffa/SublimeKickAssemblerC64/blob/d8cb11f0b6155f32e4d659e3686f2b3ad1a5dba2/kickass_build.py#L50

**Comment by daleicious** [comment]
Hi Swoffa - thanks for putting this package together! So helpful! I noticed though while debugging in windows, that the monitor file name has an ")" at the end... looks like a typo in this line. It prevents the monitor file from being passed to VICE. I removed the ) from this line (locally) and it did the trick. Thought I'd let you know. Thanks again!

**Comment by Swoffa** [comment]
Thank you so much for pointing this out. Will be fixed!
