### ISSUE TITLE
Settings doesn't work

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#32]
Windows 10 - menu items doesn't work.

* Readme - opens a blank document names readme.md
* Both the preferences and settings options gives an error requester that the file couldn't be opened.

**Comment by Swoffa** [comment]
Thanks for reporting this issue. Will be fixed.
Menu entries currently only works when package is cloned from GitHub (either manually or with Package Control `Add Repository`/`Install Package`.

**Comment by BacchusFLT** [comment]
I deleted the installation and reinstalled it, but the issue was still the same.

(Not sure if I have fiddled with the installation but previously I got syntax highlighting for files with the extension ASM but the new instance also does it for S)

**Comment by Swoffa** [comment]
Fixed in version 1.2.5
