### ISSUE TITLE
Override debug_commands in plugin settings

### ISSUE THREAD

**Issue by arekbr** [Swoffa/SublimeKickAssemblerC64#37]
Good morning. 
I am here for the first time. Please forgive me if I put a topic in the wrong place. I would like to ask you to be able to override the debug_commands startup argument. I will try to explain my problem. 

Source It looks like this:

debugCommand = ""\"${kickass_debug_path}". ${kickass_debug_args}

real debug_command plus debug_args like this:
c64debugger.exe -autojmp -layout 11 -breakpoints bin/breakpoints.txt -symbols bin/${build_file_base_name}.vss -wait 2500 -pass -logfile "bin/yawanawa_ViceLog.txt" -moncommands "bin/yawanawa_MonCommands.mon" "bin/yawanawa.prg"

here debug_cmd starts from kickass_build.py
debugCommand = "\"${kickass_debug_path}\" ${kickass_debug_args} -logfile \"${kickass_output_path}/${build_file_base_name}_ViceLog.txt\" -moncommands \"${kickass_output_path}/${build_file_base_name}_MonCommands.mon\" -"${kickass_output_path}/${kickass_compiled_filename}\""

when I want to use C64Debugger (slajerek/samar) I need to add "-prg" through the prg file name manually. 

debugCommand = "\"${kickass_debug_path}\" ${kickass_debug_args} -logfile \"${kickass_output_path}/${build_file_base_name}_ViceLog.txt\" -moncommands \"${kickass_output_path}/${build_file_base_name}_MonCommands.mon\" -prg \"${kickass_output_path}/${kickass_compiled_filename}\""

Otherwise it doesn't want to work for me.I need -prg before \"${kickass_output_path}/${kickass_compiled_filename}\""  I've edited kickass_build.py file, but next time I update the plugin I'll probably have to do it again manually. My question is - how to override debugcmd from plugin settings and add -prg fixed

kind regards
Arek

**Comment by Swoffa** [comment]
@arekbr 
Thanks for feedback. Will try to find a good solution for this, probably what @BroneCk suggested to start with:
> Simplest thing is to move ${kickass_debug_args} just right before "${kickass_output_path}/${kickass_compiled_filename}" and then when you type in kickass_debug_args in config "-prg " it will run like a charm :)

**Comment by Swoffa** [comment]
Fixed in master, @arekbr, just put `-prg` as the last thing in your `kickass_debug_args` setting and it should work fine.
