### ISSUE TITLE
How use variable in debug_args?

### ISSUE THREAD

**Issue by arekbr** [Swoffa/SublimeKickAssemblerC64#43]
Hello again

Something I don't understand or can't I do it?

I want to use the variable in debug_args for C64Debugger. But it doesn't work for me. Maybe I do something wrong? 

That's what the settings looks like (debug_arg):
"kickass_debug_args": "-layout 11 -breakpoints bin/breakpoints.txt -symbols \"${kickass_output_path}/${build_file_base_name}.vs\" -wait 1750 -pass -prg",

That's how the command looks like 
"C64Debugger" -logfile "bin/yawanawa_ViceLog.txt" -moncommands "bin/yawanawa_MonCommands.mon" -layout 11 -breakpoints bin/breakpoints.txt -symbols "${kickass_output_path}/${kickass_compiled_filename}" -wait 1750 -pass -prg "bin/yawanawa.prg"

expected: 
"C64Debugger" -logfile "bin/yawanawa_ViceLog.txt" -moncommands "bin/yawanawa_MonCommands.mon" -layout 11 -breakpoints bin/breakpoints.txt -symbols "bin/yawanawa.vs" -wait 1750 -pass -prg "bin/yawanawa.prg"

kind regards
Arek

**Comment by Swoffa** [comment]
Fixed in `master`. Variables in settings `kickass_args`, `kickass_run_args` and `kickass_debug_args` is now resolved.

**Comment by Swoffa** [comment]
> Hello. variable in debug_args is ok now, but something wrong with "kickass_compiled_filename" args:
> 
> Look at this generated command: after -prg option. Expected yawanawa.prg
> 
> "c64debugger.exe" -logfile "bin/yawanawa_ViceLog.txt" -moncommands "bin/yawanawa_MonCommands.mon" -autojmp -layout 11 -breakpoints bin/breakpoints.txt -symbols bin/yawanawa.vss -wait 2500 -pass -prg "bin/${build_file_base_name}.prg"

Fixed!
