### ISSUE TITLE
Not using my PATH on Linux

### ISSUE THREAD

**Issue by hayesmaker** [Swoffa/SublimeKickAssemblerC64#48]
java is on my PATH variable:
```
echo $PATH
/home/hayesmaker64/Workspace/java/jdk-11.0.1/bin:/home/hayesmaker64/Workspace/java/jdk-11.0.1/bin:/home/hayesmaker64/.npm-global/bin:/home/hayesmaker64/bin:/home/hayesmaker64/.local/bin:/home/hayesmaker64/.nvm/versions/node/v10.4.1/bin:/home/hayesmaker64/.rvm/gems/ruby-2.0.0-p648/bin:/home/hayesmaker64/.rvm/gems/ruby-2.0.0-p648@global/bin:/usr/share/rvm/rubies/ruby-2.0.0-p648/bin:/home/hayesmaker64/.npm-global/bin:/home/hayesmaker64/bin:/home/hayesmaker64/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/rvm/bin:/home/hayesmaker64/Workspace/java/jdk-11.0.1/bin

java --version
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

```

but when I build in sublime it has a much shorter path and complains about missing Java
```
bash: java: command not found
[Finished in 0.0s with exit code 127]
[shell_cmd: java cml.kickass.KickAssembler "GoatPowerExample.asm" -log "bin/GoatPowerExample_BuildLog.txt" -o "bin/GoatPowerExample.prg" -vicesymbols -showmem -symbolfiledir "bin"  && "x64" -logfile "bin/GoatPowerExample_ViceLog.txt" -moncommands "bin/GoatPowerExample.vs"  "bin/GoatPowerExample.prg"]
[dir: /home/hayesmaker64/Workspace/c64/hai-world]
[path: /home/hayesmaker64/.npm-global/bin:/home/hayesmaker64/bin:/home/hayesmaker64/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]
```

**Comment by BroneCk** [comment]
Try to add PATH env to ~/.profile or if you want Xsession specific env just use .xsessionrc
X DM is not parsing .bashrc so maybe here is the problem
After you change something in .profile or .xsessionrc you should reload DM

**Comment by Swoffa** [comment]
Thanks @BroneCk 
I am lame when it comes to Linux. But also, earlier [this page](https://www.erol.name/configure-sublime-editor-kickass-debian-8-jessie/) helped people get things working on Linux.

**Comment by hayesmaker** [comment]
not working:

this is `~/.profile`

```
# User specific environment
PATH="$HOME/.local/bin:$HOME/bin:$PATH:/home/hayesmaker64/Workspace/java/jdk-11.0.1/bin"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
# User specific aliases and functions
CLASSPATH="/home/hayesmaker64/Workspace/c64/kickass/KickAss.jar"
export CLASSPATH
```
i closed and opened Sublime and press F7 to build and get this error:

```
Error: Could not find or load main class cml.kickass.KickAssembler
Caused by: java.lang.ClassNotFoundException: cml.kickass.KickAssembler
[Finished in 0.2s with exit code 1]
[shell_cmd: java cml.kickass.KickAssembler "08-first-assem.asm" -log "bin/08-first-assem_BuildLog.txt" -o "bin/08-first-assem.prg" -vicesymbols -showmem -symbolfiledir "bin"   && "x64" -logfile "bin/08-first-assem_ViceLog.txt" -moncommands "bin/08-first-assem.vs"  "bin/08-first-assem.prg"]
[dir: /home/hayesmaker64/Workspace/c64/hai-world]
[path: /home/hayesmaker64/.local/bin:/home/hayesmaker64/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin]
```

**Comment by hayesmaker** [comment]
i had to create that ~/.profile file but there exists already ~/.bash_profile

should i use be using that?

**Comment by Swoffa** [comment]
> not working:
Getting closer, now java works, but Kick Assembler is not in your CLASSPATH.
See the end of [this](https://www.erol.name/configure-sublime-editor-kickass-debian-8-jessie/), or simply put the **full path including jar-file** to `KickAss.jar` in your sublime `kickass_jar_path` setting.

Also some more info on CLASSPATH [here](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/588442#588442).

**Comment by Swoffa** [comment]
> i had to create that ~/.profile file but there exists already ~/.bash_profile
> 
> should i use be using that?

I dont know, maybe @BroneCk can help out?

**Comment by BroneCk** [comment]
@hayesmaker .bash_profile is parsed only by bash, and everything you insert into .profile should be readable by every software running directly from X and also by bash, so it's more efficient to use ~/.profile

**Comment by BroneCk** [comment]
@hayesmaker and for the info about not found kickass compiler maybe there is a typo in path (Linux is case sensitive), or access rights are wrong for user.

**Comment by hayesmaker** [comment]
the path is correct in my ~/.profile... should i be checking the access rights of that .jar file or the ~/.profile?

**Comment by BroneCk** [comment]
the jar file. 
java is working so the PATH env from .profile is parsed properly. I have the CLASSPATH in my profile like yours
-----
CLASSPATH="/home/marek/kickass/KickAss.jar"
export CLASSPATH
-----

marek@BroneCk:~$ export 
declare -x CLASSPATH="/home/marek/kickass/KickAss.jar"

and also running sublime directly from icon works fine on my Debian without kickass_jar_path setting. But as @Swoffa said you can always declare kickass_jar_path directly in sublime config

**Comment by Swoffa** [comment]
@hayesmaker Any success yet?

**Comment by Swoffa** [comment]
@hayesmaker Closing this. Reopen if it still doesn't work.

**Comment by hayesmaker** [comment]
Yeah I got it working - thanks for all the help!
