### ISSUE TITLE
A way to specify the "main" project file to be compiled regardless of active file

### ISSUE THREAD

**Issue by og2t** [Swoffa/SublimeKickAssemblerC64#51]
Hi Swoffa,

I am not sure if this has been addressed already – the case is that I like to have multiple `.asm` files per one intro/demopart (e.g. `main.asm`, `assets.asm`, `tables.asm` etc.)

Is there a way to specify a "main" file (in this case `main.asm`) that will __always__ get compiled no matter which file is actually active in Sublime?
Very often I am tweaking some values in `tables.asm` and that file would be compiled when `F7` is pressed, which doesn't make much sense.

Thanks!
Digger/ESM

**Comment by Swoffa** [comment]
Yes, there is.

If you use **Build Startup** (`Super+Shift+B / Ctrl+Shift+B`), **Build and Run Startup** (`F5`) or **Build and Debug Startup** (`Shift+F5`) the file `Startup.asm` will get compiled regardless of which file is currently active in sublime. The name `Startup` is configurable thru the `kickass_startup_file_path` setting. The startup-file needs to be in the same folder as the currently active file, but configuration for this is coming (#38).

Maybe confusing that the term startup is used, should probably be the term main.

**Comment by og2t** [comment]
Ah yes, that's what startup means, I thought it was something to do with `// @kickass-build "file-to-run": "filename.prg"`. What is this one doing? Tack!

**Comment by Swoffa** [comment]
> Also, would it be possible to configure the kickass_startup_file_path per project in any way? Just want to avoid tons of startup.prg files ;-)
Thats what PR #38 is all about, to configure where to find the startup file of you have many folders. Will try to finish it soon.

>Ah yes, that's what startup means, I thought it was something to do with // @kickass-build "file-to-run": "filename.prg". What is this one doing?
The `file-to-run` annotation is a way to tell the build system which prg to start, if several are created (using Kick Assembler segments):
```
// @kickass-build "file-to-run": "StartupSegment.prg"
 
.segment Startup [outPrg="StartupSegment.prg"]
:BasicUpstart2(startup)
startup:
inc $d020
jmp *-3
 
.segment Another [outPrg="AnotherSegment.prg"]
:BasicUpstart2(another)
another:
inc $d021
jmp *-3
```

**Comment by og2t** [comment]
Thanks Bacchus. Yeah, I am using `#import` a lot, I've sorted it out with `F5` and custom `kickass_startup_file_path` setting for the `main` file.

Your stuff runs as `default_pretbuild_path/default_postbuild_path` I assume?

Is `F8` used to compile to `.d64` then?

It would be good to add these PR manuals to the `README` at once, there's a lot of undocumented features ;-)

**Comment by BacchusFLT** [comment]
Tomek,

To qualify the answer.

I posted the make.bat so show what I ran using F8. The last line assemblers
"build d64.asm" .. When I did Count Duckula last week, that file contains
this:

.disk [filename = "release\count duckula.d64", name = "*COUNT DUCKULA*", id
="FLT"]
{
[name ="CT.DUCKULA+5/FLT", type="prg", prgFiles = "crunched\main-game.prg"],
[name ="CT.DUCKULA DOCS ", type="prg", prgFiles = "Crunched\docs.prg"],
[name ="CT.DUCKULA PIC  ", type="prg", prgFiles = "Crunched\picview.prg"],

[name =
@"\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0",
type="del"],
[name =
@"\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0",
type="del"],
[name =
@"\$d5\$c3\$c4\$c5\$c5\$c9\$d5\$c5\$c9\$d5\$c3\$c4\$c5\$c5\$c4\$c9",
type="del"],
[name =
@"\$ca\$c9\$ac\$c6\$d2\$cb\$c2\$20\$c7\$c7\$20\$20\$20\$af\$d2\$cb",
type="del"],
[name =
@"\$a4\$c8\$c8\$a4\$a4\$a4\$c7\$20\$a5\$ca\$c4\$b7\$a5\$c7\$a4\$a4",
type="del"],
[name =
@"\$d5\$cb\$ad\$c4\$c9\$af\$a5\$a7\$af\$af\$af\$af\$d4\$c2\$af\$af",
type="del"],
[name =
@"\$ca\$ae\$b0\$c6\$cb\$b9\$a5\$c8\$b9\$b9\$b9\$b9\$a5\$aa\$b9\$b9",
type="del"],
[name =
@"\$a2\$c7\$c8\$a2\$a2\$aa\$20\$c2\$af\$d2\$c6\$c9\$a5\$20\$a5\$a2",
type="del"],
[name =
@"\$a2\$d4\$d9\$a2\$a2\$c8\$20\$b7\$20\$20\$20\$c8\$c7\$20\$c7\$a2",
type="del"],
[name =
@"\$b8\$ca\$cb\$b8\$b8\$ca\$c3\$c4\$c5\$c4\$c3\$cb\$ca\$c6\$cb\$b8",
type="del"],
[name =
@"\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0\$c0",
type="del"],
}

Again, this is purely a Kick Assembler question. Sublime allows to to edit
the file and Simon's "glue" gives you access to the function (F8)  that
runs a named bat file. You need to define that make file of course, so this
is merely saving you running it via shell och clicking it.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den fre 18 jan. 2019 kl 09:51 skrev Tomek Augustyn <notifications@github.com
