### ISSUE TITLE
Source option to compile other sourcefile rather than current

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#57]
In general, I feel the functionality has a bit of an over-investment in a hardcoded file called "startup.asm", with a plethora of keypresses locked up to support it. The whole idea - I guess - is to have a project masterfile that is easily accessible. Two thoughts in this context:

1) How about making the name of this "project mainfile" selectable? (I also assume it's not possible to make this selectable per project but only generally for the installation of the plugin - per project would be preferable if possible).

2) I keep compiling files that are parts of a project and get errors as it misses definitions in the master files. Would it be possible to add a "pseudo thing" in the "daughter files" referencing the "mother", so that pressing F7 would compile the mother? (Or can this already be achieved with the prebuild options or @kickass-build?)

**Comment by Swoffa** [comment]
1. Glad you asked @BacchusFLT , since there is already a setting for this: `kickass_startup_file_path`.  As all settings it can be set globally or per project, more info here: https://www.sublimetext.com/docs/3/projects.html
The name of the setting is a bit confusing, and could certainly be more clear.

**Comment by Swoffa** [comment]
2. This is something I have been considering, so now that you mention it I will give it some more priority. Thanks! :)

**Comment by Swoffa** [comment]
@BacchusFLT A feature for this has now been released:
https://goatpower.org/2021/03/08/version-1-3-4-of-kick-assembler-package-for-sublime/
