### ISSUE TITLE
Path to VICE

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#58]
In the recent versions of VICE, the binaries are not in the root folder of the VICE directory, but under bin/

**Comment by Swoffa** [comment]
Fixed, although, it is not available thru Sublime Package Control until next "official" release.

**Comment by BacchusFLT** [comment]
Thanks .. Looking forward to this. Did you update it or did you make some
magic support for both alternatives?

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den mån 13 juli 2020 kl 11:15 skrev Simon Oskarsson <
notifications@github.com>:

**Comment by BacchusFLT** [comment]
I have tried to apply updates, but to the best of my understanding it still
runs Vice from the root and not from the bin dir. We are pushing a month
since you made the change so I'm just curious on how long we need to wait
...

The question is still pending if you made this selectable, made a hard
change or it does background magic to handle both.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 Skype: BacchusBerg
 Hangout: pontus.bergatrollet@gmail.com
 www.bergatrollet.se


Den mån 13 juli 2020 kl 11:15 skrev Simon Oskarsson <
notifications@github.com>:

**Comment by Swoffa** [comment]
Sorry for the delayed answer.

> I have tried to apply updates, but to the best of my understanding it still runs Vice from the root and not from the bin dir. We are pushing a month since you made the change so I'm just curious on how long we need to wait ... 
Update is only available if you clone the package from GitHub. I will make a release soon so that it will also be available thru Sublime Package control.

>The question is still pending if you made this selectable, made a hard change or it does background magic to handle both. 
It has "background magic", bin is preferred but root will also work. And, it is always possible to configure the location of the Vice executable by customizing the `kickass_run_path` and/or `kickass_debug_path` settings.

**Comment by Swoffa** [comment]
@BacchusFLT The fix is now available thru Package control in Sublime, just update the pavkage.

**Comment by BacchusFLT** [comment]
Den tors 13 aug. 2020 kl 10:26 skrev Simon Oskarsson <
notifications@github.com>:

> Sorry for the delayed answer.
>
For sure no worries. One shouldn't entertain any SLA in relation to
non-paying customers .-)


> I have tried to apply updates, but to the best of my understanding it
> still runs Vice from the root and not from the bin dir. We are pushing a
> month since you made the change so I'm just curious on how long we need to
> wait ...
> Update is only available if you clone the package from GitHub. I will make
> a release soon so that it will also be available thru Sublime Package
> control.
>
> The question is still pending if you made this selectable, made a hard
> change or it does background magic to handle both.
> It has "background magic", bin is preferred but root will also work. And,
> it is always possible to configure the location of the Vice executable by
> customizing the kickass_run_path and/or kickass_debug_path settings.
>
>
Super cool. I guess one should expect that the new and old scenarios are
going to work in parallel for the foreseeable future, so that look great.
