### ISSUE TITLE
GoatPowerExample.asm

### ISSUE THREAD

**Issue by AlpBilgin** [Swoffa/SublimeKickAssemblerC64#7]
So, I followed the instructions [here](https://goatpower.org/projects-releases/sublime-package-kick-assembler-c64/) and ran the example, and [this](http://prntscr.com/ijnbzv) is what I saw.

Is this what I am supposed to see?

**Comment by Swoffa** [comment]
Yes, that is exactly what you are supposed to see.
Your C64 development environment seems fine. :)

**Comment by AlpBilgin** [comment]
It would be really helpful if you put a screenshot to the instructions. [I actually started to change code too thanks for the infrastructure.](http://prntscr.com/ik4b8v)
