### ISSUE TITLE
Make won't work ...

### ISSUE THREAD

**Issue by BacchusFLT** [Swoffa/SublimeKickAssemblerC64#72]
I believe it was in a major update to Sublime that the F8 for Make.bat stopped working for me. That was an update that also forced me to pay, which I eventually did but to my surprise the make.bat still doesn't work.

I ensured that my project is in a path with no spaces, to eliminate that potential source of error. 

![image](https://user-images.githubusercontent.com/28536010/142296597-868aabbc-82fd-4753-8610-4e3aabc87128.png)

Pressing F8 is claims there is no make.bat at the location but there IS!

**Comment by simonoskarsson1337** [comment]
Thank you for bringing this to my attention @BacchusFLT. Will check!

**Comment by Swoffa** [comment]
Thank you for bringing this to my attention @BacchusFLT. Will investigate.

**Comment by Swoffa** [comment]
@BacchusFLT This is now fixed. An update will be available thru package control shortly.

**Comment by BacchusFLT** [comment]
Many thanks. What was the issue?

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den tors 18 nov. 2021 kl 12:29 skrev Simon Oskarsson <
***@***.***>:

**Comment by Swoffa** [comment]
> Many thanks. What was the issue?

The working path is not set to the source file folder inside the build script anymore, so I had to set it. It is a bit unclear when this actually changed.

**Comment by BacchusFLT** [comment]
Interesting. I have had the experience that running the bat file from a
shell and pressing f8 would yield the end result in different folders.
Let's see if that issue is also gone then.

Den tors 18 nov. 2021 15:38Simon Oskarsson ***@***.***> skrev:
