### ISSUE TITLE
Path to Vice and Kick Assembler

### ISSUE THREAD

**Issue by bryanletcher** [Swoffa/SublimeKickAssemblerC64#8]
Have you thought about adding a something to set the build directory or where Vice and Kick Assembler is rather than having to deal with path statements?  - Thanks.

**Comment by Swoffa** [comment]
Yes. It will be in the next release. In fact it is about done, just needs some testing and integration with other features...and for that I just need some time. :)

**Comment by Swoffa** [comment]
This is now possible, in version 1.2.0. Closing issue.
