### ISSUE TITLE
make it possible to add command line args when launching vice

### ISSUE THREAD

**Issue by nurpax** [Swoffa/SublimeKickAssemblerC64#9]
i recently figured out that i can make vice launch my .prg pretty much instantly by launching x64 like this:

x64 -autostartprgmode 1 your_program.prg

would be great to be able to configure this st3 package to add this option. 

this is a major time saver. 

details here https://retrocomputing.stackexchange.com/questions/6544/is-it-possible-to-make-vice-load-prg-files-faster

**Comment by Swoffa** [comment]
Thank you for feed back and suggestion!
Setting/adding command line arguments for starting Vice is planned for, it is coming in the next version or the version after that. 

In the mean time I suggest configuring Vice with `PRG Startup Mode` set to `Inject to RAM` and save options. It will then use this option on every launch.

**Comment by Swoffa** [comment]
Thank you for feed back and suggestion!
Setting/adding command line arguments for starting Vice is planned for, it is coming in the next version or the version after that. 

In the mean time I suggest configuring Vice with `PRG Startup Mode` set to `Inject to RAM` and save options. It will then use this option on every launch.

**Comment by Swoffa** [comment]
This is now possible, in version 1.2.0. Closing issue.
